spring.application.name=AmarBoiPora

spring.data.mongodb.uri=mongodb+srv://AmarBoipora:Subhodeep2003@cluster0.pbqefm3.mongodb.net/amarboipora?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.auto-index-creation=true

jwt.secret=ReplaceWithA256BitSecretKeyAtLeast32CharactersLong
jwt.expiration=86400000